name: songlib
description: SongLib gives you access to your church songbook/hymns seamlessly that you don't have to worry about even being online once you have set up the app on your device.
publish_to: 'none'
version: 0.0.7

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  context_menus: ^1.0.2
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  drift: ^2.14.1
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.5.1
  formz: ^0.6.1
  get_it: ^7.6.6
  http: ^1.1.2
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  onboarding: ^3.1.0
  path: ^1.8.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  rxdart: ^0.27.7
  screenshot: ^2.1.0
  scroll_when_needed: ^3.0.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  skeleton_loader: ^2.0.0+4
  statsfl: ^2.3.0
  styled_widget: ^0.4.1
  textstyle_extensions: ^2.0.0-nullsafety
  timeago: ^3.2.2
  upgrader: ^8.4.0
  url_launcher: ^6.2.3
  wakelock: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.14.1
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/images/
    - assets/locale/
    - assets/sound/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf

targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true

msix_config:
  display_name: SongLib - Songs of Worship
  publisher_display_name: Jackson Siro
  identity_name: 49927JackonSiro.SongLib-SongsofWorship
  publisher: CN=FF945805-BB5A-4BF1-8668-776816B557C6
  msix_version: 1.0.0.0
  logo_path: assets\icon\app_icon.png
  architecture: x64
  capabilities: internetClient
  app_installer:
    publish_folder_path: D:\Dev\Flutter\Projects\SongLib\build\windows
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: false
    force_update_from_any_version: false
  