name: songlib
description: "SongLib gives you access to your church songbook/hymns seamlessly that you don't have to worry about even being online once you have set up the app on your device."
publish_to: 'none'
version: 1.0.792

environment:
  sdk: ^3.5.4

dependencies:
  card_swiper: ^3.0.1
  context_menus: ^2.0.0+1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  firebase_analytics: ^11.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_performance: ^0.10.1
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.6.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.2.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  sentry_flutter: ^8.11.1
  share_plus: ^10.1.4
  shared_preferences: ^2.3.3
  sizer: ^3.0.5
  skeleton_loader: ^2.0.0+4
  sqflite: ^2.4.1
  styled_widget: ^0.4.1
  textstyle_extensions: ^2.0.0-nullsafety
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  desktop_window: ^0.4.2
  wakelock_plus: ^1.2.10

dev_dependencies:
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  msix: ^3.16.8
    
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf

msix_config:
  display_name: SongLib - Songs of Worship
  publisher_display_name: Jackson Siro
  identity_name: 49927JackonSiro.SongLib-SongsofWorship
  publisher: CN=FF945805-BB5A-4BF1-8668-776816B557C6
  msix_version: 1.0.7.65
  logo_path: assets\icons\app_icon.png
  architecture: x64
  capabilities: internetClient
  app_installer:
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: false
    force_update_from_any_version: false