name: songlib
description: SongLib gives you access to your church songbook/hymns seamlessly that you don't have to worry about even being online once you have set up the app on your device.
publish_to: 'none'
version: 0.0.7

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  card_swiper: ^2.0.4
  carousel_slider: ^4.1.1
  collection: ^1.15.0
  connectivity_plus: ^3.0.3
  context_menus: ^1.0.2
  cupertino_icons: ^1.0.2
  dartx: ^0.7.1
  drift: ^1.7.1
  desktop_window: ^0.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_keyboard_visibility: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_platform_alert: ^0.3.0
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  http: ^0.13.5
  icapps_architecture:
      git:
        url: https://github.com/Oyonde/icapps-architecture.git
  injectable: ^1.5.3
  intl: ^0.18.1
  json_annotation: ^4.6.0
  niddler_dart: ^1.5.0
  onboarding: ^3.1.0
  parse_server_sdk_flutter: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.8
  percent_indicator: ^4.2.2
  provider: ^6.0.3
  rxdart: ^0.27.7
  screenshot: ^1.2.3
  scroll_when_needed: ^2.0.0
  sentry_flutter: ^6.9.1
  share_plus: ^4.0.10
  shared_preferences: ^2.0.11
  skeleton_loader: ^2.0.0+4
  statsfl: ^2.0.1-nullsafety
  styled_widget: ^0.3.1
  sqlite3_flutter_libs: ^0.5.2
  synchronized: ^3.0.0+2
  storage_inspector: ^0.1.1
  textstyle_extensions: ^2.0.0-nullsafety
  timeago: ^3.3.0
  upgrader: ^6.0.0
  url_launcher: ^6.1.2
  wakelock: ^0.6.2
  workmanager: ^0.5.0

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^1.7.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  license_generator: ^1.0.5
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  msix: ^3.7.0
  model_generator: ^5.8.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/images/
    - assets/locale/
    - assets/sound/
  fonts:
    - family: TrebuchetMS
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf

icapps_license:
  nullsafety: true
  licenses:
    device_info: 'https://raw.githubusercontent.com/flutter/plugins/master/packages/device_info/device_info/LICENSE'
    flutter_cache_manager: 'https://raw.githubusercontent.com/Baseflow/flutter_cache_manager/develop/flutter_cache_manager/LICENSE'

targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true

msix_config:
  display_name: SongLib - Songs of Worship
  publisher_display_name: Jackson Siro
  identity_name: 49927JackonSiro.SongLib-SongsofWorship
  publisher: CN=FF945805-BB5A-4BF1-8668-776816B557C6
  msix_version: 1.0.0.0
  logo_path: assets\icon\app_icon.png
  architecture: x64
  capabilities: internetClient
  app_installer:
    publish_folder_path: D:\Dev\Flutter\Projects\SongLib\build\windows
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: false
    force_update_from_any_version: false
  